### ISSUE TITLE
UC01 Realizar Autenticação

### ISSUE THREAD

**Issue by cantuariavc** [DSW-2018/projetoDesenho#22]
## Descrição

Tem como objetivo fazer com que o cliente se identifique para o sistema, para que o sistema possa fornecer as informações corretamente a cada cliente.

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.

## Tasks

- [x]  Login
- [ ]  Logout

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui nome significativo.

**Comment by MateusO97** [comment]
Resolvido em #52 e #50
