### ISSUE TITLE
UC04 Confirmar preço

### ISSUE THREAD

**Issue by cantuariavc** [DSW-2018/projetoDesenho#26]
## Descrição

Tem como objetivo confirmar se o preço de um determinado produto está correto, caso o produto seja dado como confiavel, os usuários ganham 1 ponto de confiança, caso o produto seja dado como não confiavel, os usuários perdem 1 pontos de confiança

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.

## Tasks

Diga as tarefas para conclusão.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui nome significativo.

**Comment by MateusO97** [comment]
Resolvido em #53
