### ISSUE TITLE
UC12 Pontuar Confiabilidade do Produto

### ISSUE THREAD

**Issue by cantuariavc** [DSW-2018/projetoDesenho#37]
## Descrição

A confiabilidade do preço de um produto será determinada através das confirmações e questionamentos dos usuários, um usuário normal soma 2 pontos de confiança para um produto, um usuário não confiavel soma 1 ponto de confiança e um usuário premium soma 3 pontos de confiança

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.

## Tasks

Diga as tarefas para conclusão.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui nome significativo.

**Comment by MateusO97** [comment]
Resolvido em #53
